apiVersion: v1
kind: Service
metadata:
  name: decisionmaker
  namespace: kube-system
  labels:
    app: decisionmaker
spec:
  ports:
    - port: 8080
      targetPort: 8080
  clusterIP: None 
  selector:
    app: decisionmaker